# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='',
  serialized_pb=_b('\n\x0c\x43ommon.proto\"B\n\tS2CPrompt\x12\x10\n\x08promptId\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x03(\t\x12\x14\n\x0cprotocolCode\x18\x03 \x01(\x05\x42\x38\n\'com.janlr.ag.cellwar.common.fixed.protoB\x0b\x43ommonProtoH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_S2CPROMPT = _descriptor.Descriptor(
  name='S2CPrompt',
  full_name='S2CPrompt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='promptId', full_name='S2CPrompt.promptId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='S2CPrompt.param', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocolCode', full_name='S2CPrompt.protocolCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['S2CPrompt'] = _S2CPROMPT

S2CPrompt = _reflection.GeneratedProtocolMessageType('S2CPrompt', (_message.Message,), dict(
  DESCRIPTOR = _S2CPROMPT,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:S2CPrompt)
  ))
_sym_db.RegisterMessage(S2CPrompt)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'com.janlr.ag.cellwar.common.fixed.protoB\013CommonProtoH\003'))
# @@protoc_insertion_point(module_scope)
